app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


//----------------------- Panel Routes Here

Route::group(['middleware' => ['auth']], function () {

//    Panel index Route

    Route::get('/panel', function () {
        return view('panel.index');
    });

//    Clubs Routes

    Route::resource('panel/clubs', 'Panel\ClubsController');

//    Teams Routes

    Route::get('panel/teams', 'Panel\TeamsController@index');
    Route::get('panel/teams/create', 'Panel\TeamsController@create');
    Route::post('panel/teams/create', 'Panel\TeamsController@store');
    Route::get('panel/teams/edit/{teamId}', 'Panel\TeamsController@edit');
    Route::post('panel/teams/edit/{teamId}', 'Panel\TeamsController@update');
    Route::post('panel/teams/delete/{teamId}', 'Panel\TeamsController@delete');
    Route::post('panel/teams/gallery/{imageId}', 'Panel\TeamsController@deleteGalleryImage');

//    Players Routes

    Route::get('panel/players', 'Panel\PlayersController@index');
    Route::get('panel/players/create', 'Panel\PlayersController@create');
    Route::post('panel/players/create', 'Panel\PlayersController@store');
    Route::get('panel/players/edit/{playerId}', 'Panel\PlayersController@edit');
    Route::post('panel/players/edit/{playerId}', 'Panel\PlayersController@update');
    Route::post('panel/players/delete/{playerId}', 'Panel\PlayersController@delete');
    Route::post('panel/players/gallery/{playerId}', 'Panel\PlayersController@deleteGalleryImage');

//    Seasons Routes

    Route::get('panel/seasons', 'Panel\SeasonsController@index');
    Route::get('panel/seasons/create', 'Panel\SeasonsController@create');
    Route::post('panel/seasons/create', 'Panel\SeasonsController@store');
    Route::get('panel/seasons/edit/{seasonId}', 'Panel\SeasonsController@edit');
    Route::post('panel/seasons/edit/{seasonId}', 'Panel\SeasonsController@update');
    Route::post('panel/seasons/delete/{seasonId}', 'Panel\SeasonsController@delete');

//    Competitions Routes

    Route::get('panel/competitions', 'Panel\CompetitionsController@index');
    Route::get('panel/competitions/create', 'Panel\CompetitionsController@create');
    Route::post('panel/competitions/create', 'Panel\CompetitionsController@store');
    Route::get('panel/competitions/edit/{competitionId}', 'Panel\CompetitionsController@edit');
    Route::post('panel/competitions/edit/{competitionId}', 'Panel\CompetitionsController@update');
    Route::post('panel/competitions/delete/{competitionId}', 'Panel\CompetitionsController@delete');

//    Matches Routes

    Route::get('panel/matches', 'Panel\MatchesController@index');
    Route::get('panel/matches/create', 'Panel\MatchesController@create');
    Route::post('panel/matches/create', 'Panel\MatchesController@store');
    Route::get('panel/matches/edit/{matchId}', 'Panel\MatchesController@edit');
    Route::post('panel/matches/edit/{matchId}', 'Panel\MatchesController@update');
    Route::post('panel/matches/delete/{matchId}', 'Panel\MatchesController@delete');

    Route::get('panel/matches/seasonCompetitions/{seasonId}', 'Panel\MatchesController@getSeasonCompetitions');

});


// ----------------------------- Site Routes

Route::get('/', 'Site\SiteController@index');
Route::get('/teams', 'Site\SiteController@teams');
Route::get('/competitions', 'Site\SiteController@competitions');
Route::get('/clubs', 'Site\SiteController@clubs');
Route::get('/teams/{teamId}', 'Site\SiteController@showTeam');
Route::get('/team/players/{playerId}', 'Site\SiteController@showPlayer');
Route::get('/seasons/', 'Site\SiteController@seasons');
Route::get('/seasons/{seasonId}', 'Site\SiteController@showSeason');
Route::get('/competitions/{competitionId}', 'Site\SiteController@showCompetition');

// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

app/Player.php
<?php

namespace LaravelTask;

use Illuminate\Database\Eloquent\Model;

class Player extends Model
{
    //
    public function GalleryImages()
    {
        return $this->hasMany('LaravelTask\PlayerGallery', 'player_id');
    }

    public function team()
    {
        return $this->belongsTo('LaravelTask\Team', 'team_id');
    }

    public function getFavoriteFootAttribute($value)
    {
        if ($value == 'R') {
            return 'Right';
        } else {
            return 'Left';
        }
    }
}

app/Http/Controllers/Site/SiteController.php
<?php

namespace LaravelTask\Http\Controllers\Site;

use Illuminate\Http\Request;

use LaravelTask\Club;
use LaravelTask\Competition;
use LaravelTask\Http\Requests;
use LaravelTask\Http\Controllers\Controller;
use LaravelTask\Player;
use LaravelTask\Season;
use LaravelTask\Team;

class SiteController extends Controller
{

    public function index()
    {
        $teams = Team::paginate(5);
        $competitions = Competition::paginate(5);
        $clubs = Club::paginate(5);
        return view('site.index', compact('teams', 'competitions', 'clubs'));
    }

    public function teams()
    {
        $teams = Team::paginate(6);
        return view('site.teams', compact('teams'));
    }

    public function competitions()
    {
        $competitions = Competition::paginate(6);
        return view('site.competitions', compact('competitions'));
    }

    public function seasons()
    {
        $seasons = Season::paginate(10);
        return view('site.seasons', compact('seasons'));
    }

    public function showSeason($seasonId)
    {
        $season = Season::findOrFail($seasonId);
        return view('site.singleSeason', compact('season'));
    }

    public function showCompetition($competitionId)
    {
        $competition = Competition::findOrFail($competitionId);
        return view('site.singleCompetition', compact('competition'));
    }

    public function clubs()
    {
        $clubs = Club::paginate(6);
        return view('site.clubs', compact('clubs'));
    }

    public function showTeam($teamId)
    {
        $team = Team::findOrFail($teamId);
        return view('site.singleTeam', compact('team'));
    }

    public function showPlayer($playerId)
    {
        $player = Player::findOrFail($playerId);
        return view('site.singlePlayer', compact('player'));
    }

}

resources/views/site/competitions.blade.php
@extends('site.layout')

resources/views/site/index.blade.php
@extends('site.layout')
@section('content')
    <h3> Teams </h3>

    <table class="table table-hover">
        <thead>
        <tr>
            <th> #</th>
            <th> team</th>
            <th> Logo</th>
            <th> players</th>
        </tr>
        <tbody>
        @foreach($teams as $team)
            <tr>
                <td> {{ $team->id }} </td>
                <td><a href="{{ url('/teams/'.$team->id) }}"> {{ $team->name }} </a></td>
                <td>
                    <img src="{{ asset($team->logo) }}" alt="">
                </td>
                <td> {{ $team->players->count() }} </td>
            </tr>
        @endforeach
        </tbody>
        </thead>
    </table>
    <div class="pagination"> {!! $teams->render() !!} </div>

    <hr>

    <h3> Competitions </h3>

    <table class="table table-hover">
        <thead>
        <tr>
            <th> #</th>
            <th> competition</th>
            <th> season</th>

        </tr>
        <tbody>
        @foreach($competitions as $competition)
            <tr>
                <td> {{ $competition->id }} </td>
                <td><a href="{{ url('/competitions/'.$competition->id) }}"> {{ $competition->name }} </a></td>
                <td>
                    <p> {{ $competition->season->name }} </p>
                </td>
            </tr>
        @endforeach
        </tbody>
        </thead>
    </table>
    <div class="pagination"> {!! $teams->render() !!} </div>

    <hr>

    <h3> Club </h3>

    <table class="table table-hover">
        <thead>
        <tr>
            <th> #</th>
            <th> Club</th>
            <th> logo</th>

        </tr>
        <tbody>
        @foreach($clubs as $club)
            <tr>
                <td> {{ $club->id }} </td>
                <td><a href="{{ url('/clubs/'.$club->id) }}"> {{ $club->name }} </a></td>
                <td>
                    <img src="{{ asset($club->logo) }}" alt="">
                </td>
            </tr>
        @endforeach
        </tbody>
        </thead>
    </table>
    <div class="pagination"> {!! $teams->render() !!} </div>
@stop

resources/views/site/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/site/dist/css/bootstrap.min.css') }}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/site/dist/css/style.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]>
    <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{{ url('/') }}">Home</a></li>
                <li><a href="{{ url('/teams') }}">Teams</a></li>
                <li><a href="{{ url('/seasons') }}">Seasons</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">

    @yield('content')

</div><!-- /.container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
@yield('scripts')
</body>
</html>

resources/views/site/seasons.blade.php
@extends('site.layout')
@section('content')
    <style>
        * {
            text-align: center;
        }

        thead tr th {
            text-align: center;
        }
    </style>
    <div class="main col-xs-12 col-md-6">
        <h3> seasons </h3>

        <table class="table table-hover">
            <thead>
            <tr>
                <th> #</th>
                <th> season</th>
            </tr>
            <tbody>
            @foreach($seasons as $season)
                <tr>
                    <td> {{ $season->id }} </td>
                    <td><a href="{{ url('/seasons/'.$season->id) }}"> {{ $season->name }} </a></td>
                </tr>
            @endforeach
            </tbody>
            </thead>
        </table>
        <div class="pagination"> {!! $seasons->render() !!} </div>

        <hr>
    </div>
@stop

resources/views/site/singleCompetition.blade.php
@extends('site.layout')
@section('content')
    <div class="main">
        <style>
            /*            * {
                            text-align: center;
                        }

                        thead tr th {
                            text-align: center;
                        }*/
        </style>
        <div class="main col-xs-12 col-md-6">
            <h3> {{ $competition->name }} / {{ $competition->season->name }}</h3>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th> #</th>
                    <th> Team name</th>
                    <th> Points</th>
                </tr>
                <tbody>
                @foreach($competition->ranks($competition->id) as $k => $com)
                    <tr>
                        <td> {{ $k+1 }} </td>
                        <td><a href="{{ url('teams/'.$com->team->id) }}"> {{ $com->team->name}} </a></td>
                        <td> {{ $com->points }} </td>
                    </tr>
                @endforeach

                </tbody>
                </thead>
            </table>

            <hr>
        </div>
    </div>
@stop

resources/views/site/singlePlayer.blade.php
@extends('site.layout')
@section('content')
    <style>
        .player {
            margin-top: 20px;
        }

        h2 {
            text-align: center;
        }

        .profile {
            margin-bottom: 15px;
        }

        .profile img {
            width: 100%;
            height: 350px;
        }

        ul li img {
            width: 100%;
            height: 150px;
            margin-bottom: 15px;
        }
    </style>
    <div class="player">
        <div class="row">
            <div class="col-xs-6">
                <div class="profile">
                    <h2> Player Name: {{ $player->name }} </h2>
                    <img src="{{ asset($player->photo) }}" alt="">
                </div>
                <div class="others">
                    <ul class="row list-unstyled">
                        <li><span> Birth Date : </span><span class="pull-right"> {{ date('d/m/Y',strtotime
                        ($player->birth_date)) }}
                            </span>
                        </li>
                        <li>
                            <span> Age: </span>
                            <span class="pull-right"> {{ $player->age }} year </span>
                        </li>
                        <li>
                            <span> Team: </span>
                            <span class="pull-right"> {{ $player->team->name }}  </span>
                        </li>

                        <li>
                            <span> Foot: </span>
                            <span class="pull-right"> {{ $player->favorite_foot }}  </span>
                        </li>

                    </ul>
                </div>
            </div>
            <div class="col-xs-6">
                <h2> gallery </h2>
                <div class="gallery">
                    <div class="small_img">
                        <ul class="row list-unstyled">
                            @foreach($player->GalleryImages as $img)
                                <li class="col-xs-4"><img src="{{ asset($img->photo) }}" alt=""></li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/site/singleSeason.blade.php
@extends('site.layout')
@section('content')
    <div class="main">
        <style>
            * {
                text-align: center;
            }

            thead tr th {
                text-align: center;
            }
        </style>
        <div class="main col-xs-12 col-md-6">
            <h3> {{ $season->name }} </h3>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th> #</th>
                    <th> competition name</th>
                    <th> logo</th>
                </tr>
                <tbody>
                @foreach($season->competitions as $competition)
                    <tr>
                        <td> {{ $competition->id }} </td>
                        <td><a href="{{ url('competitions/'.$competition->id) }}"> {{ $competition->name }} </a></td>
                        <td><img src="{{ asset($competition->logo) }}" alt=""></td>
                    </tr>
                @endforeach
                </tbody>
                </thead>
            </table>

            <hr>
        </div>
    </div>
@stop

resources/views/site/singleTeam.blade.php
@extends('site.layout')
@section('content')
    <style>
        .team {
            margin-top: 20px;
        }

        h2 {
            text-align: center;
        }

        .profile {
            margin-bottom: 15px;
        }

        .profile img {
            width: 100%;
        }

        ul li img {
            width: 100%;
            height: 150px;
            margin-bottom: 15px;
        }
    </style>
    <div class="team">
        <div class="row">
            <div class="col-xs-6">
                <div class="profile">
                    <h2> Club Name: {{ $team->name }} </h2>
                    <img src="{{ asset($team->logo) }}" alt="">
                </div>
                <div class="others">
                    <ul class="row list-unstyled">
                        <li class="col-xs-6">
                            <img src="{{ asset($team->home_kit) }}" alt="">
                            <p> Home Kit </p>
                        </li>
                        <li class="col-xs-6">
                            <img src="{{ asset($team->away_kit) }}" alt="">
                            <p> way Kit </p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-6">
                <h2> gallery </h2>
                <div class="gallery">
                    <div class="small_img">
                        <ul class="row list-unstyled">
                            @foreach($team->GalleryImages as $img)
                                <li class="col-xs-4"><img src="{{ asset($img->photo) }}" alt=""></li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <h3> players </h3>
        <ul class="row list-unstyled">
            @foreach($team->players as $player)
                <li class="col-xs-3">
                    <img src="{{ asset($player->photo) }}" alt="">
                    <h4 class="text-center"><a href="{{ url('team/players/'.$player->id) }}">{{ $player->name
                    }}</a></h4>
                </li>
            @endforeach
        </ul>
    </div>
@stop

resources/views/site/teams.blade.php
@extends('site.layout')
@section('content')
    <style>
        .main ul {
            padding: 15px;
        }

        .main ul li {
            margin-bottom: 15px;
        }

        .main ul li .team {
            padding: 15px;
            background-color: #b3faff;
            text-align: center;
        }

        .main ul li img {
            width: 100%;
            height: 250px;
        }
    </style>
    <div class="main">
        <h2> teams </h2>
        <ul class="row list-unstyled">
            @foreach($teams as $team)
                <li class="col-xs-3">
                    <div class="team">
                        <img src="{{ $team->logo }}" alt="">
                        <a href="{{ url('teams/'.$team->id) }}">{{ $team->name }}</a>
                    </div>
                </li>
            @endforeach
        </ul>

        <div class="pagination">
            {{ $teams->render() }}
        </div>
    </div>
@stop